### ISSUE TITLE
Scale is off

### ISSUE THREAD

**Issue by brandonzylstra** [wooorm/emoji-emotion#10]
There's no possible way a pouting cat has the same degree of negativity as a middle finger.  Not only are they not the same, they are at least an order of magnitude different.  The idea for this project is great, but this seemingly tiny flaw is fatal.  It cannot be used without correcting this error.

**Comment by wooorm** [comment]
Hello Brandon! Welcome to open source.

> THE SOFTWARE IS PROVIDED 'AS IS' [...] INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
[...] FITNESS FOR A PARTICULAR PURPOSE [...]
> — [MIT license](https://github.com/words/emoji-emotion/blob/master/LICENSE)

Maybe it’s not so black and white and we can discuss it? Maybe you’re into creating a PR to fix this? Or, you could fork this project and go do your thing, that’s fine as well.

> It cannot be used without correcting this error.

This project is currently, in fact, used by other projects.
