### ISSUE TITLE
I don't think 😤 should be +5

### ISSUE THREAD

**Issue by cfreeley** [wooorm/emoji-emotion#8]
I know the emoji is named triumph, but he looks super pissed off, and I don't think he should be +5. Maybe a 0 for controversial, but I've never seen him even used positively to be honest. In all browsers he, IMO, looks pretty angry. http://emojipedia.org/face-with-look-of-triumph/

**Comment by wooorm** [comment]
Hi! 👋

As noted in the [readme](https://github.com/wooorm/emoji-emotion#data), how they “look” should not matter in the scores, rather, the definitions by Unicode should matter (this case, CLDR short name, “face with steam from nose”; Unicode name, Face With Look of Triumph).

Anyway, I think you’re right in that it’s controversial: I’m :+1: on a score of `0`. Would you be willing to create a PR?

**Comment by cfreeley** [comment]
Sure thing! Thank you! Didn't see that in the readme, my bad

**Comment by wooorm** [comment]
No problem! :)

**Comment by wooorm** [comment]
Closed in c29abc5! 😤 <- neutral
